class LoadData < ActiveRecord::Migration
  def self.up
    execute "DELETE FROM units"
    execute "DELETE FROM products"
    execute "DELETE FROM recipes"
    execute "DELETE FROM recipe_steps"
    execute "DELETE FROM step_ingredients"
    execute "DELETE FROM users"
    
    execute 'Insert into Users(id, login) values (1, "DummyUser")'

    execute 'insert into units (id, name, name_plural, name_genitive) values (2	,"dl"," "	," "	)'
    execute 'insert into units (id, name, name_plural, name_genitive) values (3	,"l"," "	," "	)'
    execute 'insert into units (id, name, name_plural, name_genitive) values (7	,"g"," "	," "	)'
    execute 'insert into units (id, name, name_plural, name_genitive) values (8	,"dg"," "	," "	)'
    execute 'insert into units (id, name, name_plural, name_genitive) values (9	,"kg"," "	," "	)'
    execute 'insert into units (id, name, name_plural, name_genitive) values (15	,"dkg"," "	," "	)'
    execute 'insert into units (id, name, name_plural, name_genitive) values (16	,"brak"," "	," "	)'
    execute 'insert into units (id, name, name_plural, name_genitive) values (19	,"-"," "	," "	)'
    execute 'insert into units (id, name, name_plural, name_genitive) values (20	,"ml"," "	," "	)'
    execute 'insert into units (id, name, name_plural, name_genitive) values (28	,"dag"," "	," "	)'
    execute 'insert into units (id, name, name_plural, name_genitive) values (26	,"butelka","butelki","butelek")'
    execute 'insert into units (id, name, name_plural, name_genitive) values (23	,"główka","główki","główek")'
    execute 'insert into units (id, name, name_plural, name_genitive) values (11	,"kostka","kostki","kostek")'
    execute 'insert into units (id, name, name_plural, name_genitive) values (18	,"laska","laski","lasek")'
    execute 'insert into units (id, name, name_plural, name_genitive) values (13	,"paczka","paczki","paczek")'
    execute 'insert into units (id, name, name_plural, name_genitive) values (25	,"puszka","puszki","puszek")'
    execute 'insert into units (id, name, name_plural, name_genitive) values (24	,"pęczek","pęczki","pęczków")'
    execute 'insert into units (id, name, name_plural, name_genitive) values (4	,"szczypta","szczypty","szczypt")'
    execute 'insert into units (id, name, name_plural, name_genitive) values (22	,"opakowanie","opakowania","opakowań")'
    execute 'insert into units (id, name, name_plural, name_genitive) values (1	,"szklanka","szklanki","szklanek")'
    execute 'insert into units (id, name, name_plural, name_genitive) values (10	,"sztuka","sztuki","sztuk")'
    execute 'insert into units (id, name, name_plural, name_genitive) values (27	,"torebka","torebki","torebek")'
    execute 'insert into units (id, name, name_plural, name_genitive) values (17	,"ząbek","ząbki","ząbków")'
    execute 'insert into units (id, name, name_plural, name_genitive) values (5	,"łyżeczka","łyżeczki","łyżeczek")'
    execute 'insert into units (id, name, name_plural, name_genitive) values (6	,"łyżka","łyżki","łyżek")'

    execute 'insert into  products (id, name, name_plural, name_genitive) values(1	,"mąka"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(2	,"cukier"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(3	,"mleko"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(4	,"jajko"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(5	,"olej"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(6	,"miód"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(7	,"sód"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(8	,"cynamon"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(9	,"mleko"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(10	,"żółtko"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(11	,"cukier waniliowy"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(12	,"mąka ziemniaczana"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(13	,"proszek do pieczenia"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(14	,"mleko"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(15	,"mąka tortowa"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(16	,"margaryna"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(17	,"jabłko"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(18	,"galaretka"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(19	,"wiórek kokosowy"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(20	,"masło"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(21	,"cukier"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(22	,"kakao"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(23	,"masło"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(24	,"cukier puder"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(25	,"białko"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(26	,"galaretka owocowa"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(27	,"herbatniki"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(28	,"polewa czekoladowa"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(29	,"mąka"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(30	,"cukier puder"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(31	,"cukier"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(32	,"orzechy włoskie"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(33	,"drożdże"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(34	,"olejek migdałowy"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(35	,"wanilia"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(36	,"sól"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(37	,"wanilia"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(38	,"olejek migdałowy"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(39	,"tłuszcz"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(40	,"masa makowa"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(41	,"masa makowa"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(42	,"mak"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(43	,"rodzynki"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(44	,"orzechy"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(45	,"piwo"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(46	,"olej"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(47	,"żółty ser"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(48	,"pieprz"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(49	,"piwo"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(50	,"kalafior"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(51	,"żółty ser starty"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(52	,"buraki"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(53	,"marchew"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(54	,"pietruszka"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(55	,"papryka"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(56	,"czosnek"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(57	,"cukier"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(58	,"ocet"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(59	,"marchew"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(60	,"woda"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(61	,"kwasek cytrynowy"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(62	,"pomarańcza"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(63	,"mąka"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(64	,"jajko"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(65	,"brak"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(66	,"woda"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(67	,"ocet"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(68	,"żółtko"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(69	,"wanilia"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(70	,"mąka ziemniaczana"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(71	,"cukier puder"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(72	,"śmietana gęsta"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(73	,"proszek do pieczenia"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(74	,"ser biały"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(75	,"mleko gotowane"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(76	,"żelatyna"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(77	,"galaretka"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(78	,"mąka"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(79	,"cukier"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(80	,"zapach"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(81	,"jajko"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(82	,"olej"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(83	,"twaróg"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(84	,"kakao"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(85	,"polewa czekoladowa"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(86	,"herbatniki"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(87	,"mąka kartoflana"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(88	,"kakao"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(89	,"margaryna"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(90	,"mleko"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(91	,"śmietana"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(92	,"mąka pszenna"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(93	,"oranżada"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(94	,"woda"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(95	,"budyń z cukrem"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(96	,"mąka kartoflana"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(97	,"mąka pszenna"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(98	,"woda"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(99	,"budyń"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(100	,"masło roślinne"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(101	,"owoce"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(102	,"śmietana"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(103	,"ser"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(104	,"aromat"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(105	,"sztuczny miód"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(106	,"margaryna roztopiona"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(107	,"soda"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(108	,"cukier waniliowy"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(109	,"masło"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(110	,"olejek"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(111	,"jajko do smarowania"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(112	,"cynamon"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(113	,"jajka duże"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(114	,"oliwa"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(117	,"proszek do pieczenia"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(118	,"masło roślinne"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(119	,"smaku"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(120	,"marmolada"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(121	,"smak roztopiony"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(122	,"oliwa"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(123	,"śmietana"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(124	,"bita śmietana"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(125	,"galaretka"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(126	,"mleko"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(127	,"mąka ziemniaczana"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(128	,"sok z cytryny"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(129	,"masło roślinne"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(130	,"mięso mielone wieprzowo-wołowe"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(131	,"fix do kotletów mielonych"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(132	,"rosól z kury"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(133	,"kapusta włoska"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(134	,"włoszczyzna"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(135	,"cebula"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(136	,"pomidor"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(137	,"delikat do zup knorr"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(138	,"zasmażka błyskawiczna knorr"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(139	,"mięso mielone wołowe"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(140	,"rosół wołowy"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(141	,"pomidory bez skóry w zalewie"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(142	,"ketchup pikantny"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(143	,"koncentrat pomidorowy"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(144	,"fasola czerwona konserwowa"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(145	,"przyprawa chili"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(146	,"pieprz"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(147	,"proszek do pieczenia"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(148	,"cukier waniliowy"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(149	,"cukier puder"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(151	,"kisiel"," "	," "	)'
    execute 'insert into  products (id, name, name_plural, name_genitive) values(152	,"wywar z kości lub mięsa"," "	," "	)'

    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(1	,"Ciasto Agusi",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(2	,"Biszkopt z wiórkami",1	,1	,0 ,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(3	,"Placek z masą kokosową",1	,1	,0  ,  "")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(4	,"Ciasteczka świąteczne",1	,1	,0	,  "")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(5	,"Krem orzechowy",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(6	,"Makowiec",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(7	,"Kalafior w cieście",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(8	,"Sałatka z buraków",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(9	,"Sok",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(10	,"Napoleonki",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(11	,"Chrusty",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(12	,"Sernik na zimno",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(15	,"Chatka Baba-Jagi",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(16	,"Polewa czekoladowa",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(17	,"Krem do tortu",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(18	,"Masa do stefanka",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(19	,"Zebra",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(20	,"Karpatka",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(21	,"Babka piaskowa",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(22	,"Babka metrowiec",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(23	,"Skubaniec",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(24	,"Sernik szarpany",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(25	,"Stefanek",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(26	,"Murzynek",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(27	,"Murzynek II",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(28	,"Pieczone pierożki",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(29	,"Krem do tortu",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(31	,"Ciasto kruche z marmoladą",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(32	,"Ptasie mleczko",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(33	,"Placek ?",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(34	,"Babka ucierana",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(35	,"Kapuśniak z pulpetami",1	,6	,50	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(36	,"Zupa pikantna a la chili",1	,6	,60	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(37	,"Plecek (bez nazwy)",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(14	,"Biszkopt II",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(13	,"Biszkopt I",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(30	,"Jabłecznik",1	,1	,0	,"")'
    execute 'insert into recipes (id, name, owner_id, number_of_servings, minutes_to_prepare, description) values(38	,"Sos musztardowy",1	,1	,20	,"")'

    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (1	,1	,"Ciasto","Składniki zmiksować, piec 50 min. w ok 200 st.C.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (2	,1	,"Krem","Szklankę mleka zagotować z cukrem, drugą wymieszać z żółktiem, mąką i cukrem. Zalać i zagotować.",2)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (4	,2	,"Biszkopt","Piec około 35 min. w 180 st. C.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (5	,2	,"Masa","Mleko z cukrem i mąką ugotować jak budyń, utrzeć masę z margaryną.",2)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (6	,2	,"Jabłka","Utrzeć i zalać galaretkami - rozprowadzić",3)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (7	,2	,"Na wierzch","Usmażyć na złoty kolor i gorące wylać na masę.",4)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (8	,3	,"Ciasto","Ubić na sztywno białka. Pod koniec ubijania dodać cukier. Następnie dobrze wymieszać z żółtkami, mąką i proszkiem do pieczenia i kako. Piec 15min. w średnio nagrzanym piekarniku.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (9	,3	,"Masa","Przygotować galaretkę.\r\n\r\nWiórki gotować w mleku, mieszając aż powstanie gęsta masa. Wystudzić.\r\nUtrzeć masło z cukrem, dodać. Następnie dodać pianę z ubitych białek; wymieszać.\r\nPrzełożyć ciasto. Polać galaretką. Na wierzch dać herbatniki i posmarować polewą. Odstawić ciasto na 2-3 godziny do lodówki.\r\n",2)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (11	,4	," "	," "	,1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (10	,4	,"Ciasto","Zagniatamy składniki. Wałkujemy i robimy parami ciasteczka. Wszystkie dajemy na foremke i pieczemy.",2)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (12	,4	,"Lukier","Zmiksować.",3)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (14	,5	,"Krem","Na małym ogniu stawiamy garnuszek z mlekiem, do którego nasypaliśmy cukier. Płyn musi się gotować długi czas. Pilnować, mieszając od czasu do czasu drewnianą łyżką. Po ok. 30 minutach powinien stać się niemal przeźroczysty. Spuszczony kropelką na spodek powinien zastygać w kształcie kulistym na powierzchni szkła.\r\n\r\nDo miski wkładamy wyłuskane orzechy, zalewamy wrzącym lukrem. Na to kładziemy masło w kawałkach i całość ucieramy do spoistej masy.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (16	,6	," "	," "	,1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (15	,6	,"Makowiec","Zrobić ciasto. Ugnieść, rozwałkować - zrobić roladę.",2)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (17	,6	,"Masa makowa","Mak opłukać - gotować.\r\nPrzekręcić 2 razy przez maszynkę, włożyć do rondla na stopione masło, dodać cukier, miód, bakalie.\r\n\r\nSmażyć 10-15 minut mieszając. Do wystudzonej masy dodać pianę z białek. ",3)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (18	,6	,"Rolady","Rolady posmarować jajkiem, widelcem poprzekuwać.",4)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (20	,7	,"Kalafior","Kalafior ugotować i schłodzić.\r\n\r\nPodzielić i maczać w cieście następnie smażyć na oleju.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (19	,7	,"Ciasto","Wymieszać i zrobić ciasto.\r\n\r\nŻółty ser nie jest konieczny.",2)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (22	,9	,"Sok","Marchew pokroić i gotować do miękkości z pomarańczem w 1.5l wody. Po ugotowaniu zmiksować.\r\n\r\nOsobno przegotować 2.5l wody z cukrem i kwaskiem.\r\n\r\nWszystko połączyć i wstawić do lodówki.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (24	,10	,"Ciasto kluskowe","Ciasto zagieść, włożyć do lodówki na 30min. Wałkować na 1cm. Piec w gorącym piekarniku 15minut.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (23	,10	,"Ciasto maślane","Ciasto zagieść, włożyć do lodówki na 30min. Wałkować na 1cm. Piec w gorącym piekarniku 15minut.",2)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (25	,10	,"Krem","Zrobić jak budyń, dodać utarte żółtka z jajem i cukrem do gotującej masy. \r\n\r\nOstudzić mieszając w zimnej wodzie.",3)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (29	,14	,"-","Cukier i jaja dobrze utrzeć, następnie dodać mąkę z proszkiem i ciągle ucierać. Na koniec dodać olej.\r\nPieco około 40minut.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (30	,15	,"-","Margarynę, cukier i ser dobrze utrzeć, ułożyć na herbatniki, zalać polewą.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (31	,16	,"-","Wszystkie składniki rozpuścić na wolnym ogniu, nie dopuścić do wrzenia.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (32	,17	,"-","Cukier z margaryna dobrze utrzeć, następnie dodać śmietanę.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (33	,18	,"-","Mąkę i cukier rozpuścić w małej ilości mleka. Resztę mleka zagotować i wszystko połączyć. Po ostygnięciu dodać uprzednio utartą margarynę z cukrem i dobrze utrzeć.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (26	,11	,"-","Mąke zmieszać ze śmietaną, dodać żółtka, sól i proszek.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (27	,12	,"-","Margarynę z cukrem i jajami dobrze utrzeć, następnei dodać ser, wymieszać, na konieć dodać żelatynę umaczana w zimnej wodzie i rozpuszczonej w mleku.\r\n\r\nWstawić sernik do lodówki, następnie zalać galaretką.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (21	,8	,"-","Buraki, marchew i pietruszkę zetrzeć na grubej tarce, a paprykę i czosnek pokroić w drobną kostkę.\r\n\r\nWszystko wymieszać, dodać cukru i soli do smaku. Następnie dodać olej i ocet, wymieszać, włożyć do słoików i gotować 45minut.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (34	,19	,"-","Jaja utrzeć z cukrem, dodać mąkę z proszkiem do pieczenia, dalej ucierać.\r\nNa koniec dodawać stopniowo olej i oranżadę.\r\n\r\nGotowe ciasto podzielić na dwie części. Do jednej dodać kakao, do drugiej dwie łyżki mąki.\r\n\r\nWylewać na tortownicę po dwie łyżki na przemian.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (35	,20	,"Ciasto","Wodę zagotować, dodać margarynę, rozpuścić, dodać mąkę, trochę pogotować mocno mieszając, ostudzić. Następnie dodać jaja, mieszać.\r\n\r\nCiasto podzielic na połowę, na blaszce rozłożyć nierówno ciasto.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (36	,20	,"Masa","Ugotować budyń (użyć o połowę mniej mleka niż w przepisie), rozetrzec masło i stopniowo dodawać ostudzony budyń.",2)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (37	,20	,"-","Upieczone ciasto przełożyć kremem.",3)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (38	,21	,"-","Żółtka z margaryną i cukrem dobrze utrzec, następnie dodać mąkę z proszkiem, na koniec ubite białka.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (39	,22	,"Ciasto","Cukier z żółtkami utrzeć, dodać wodę, olej, mąkę i proszek do pieczenia, utrzeć, dodać na koniec pianę z białek. Podzielic ciasto na dwie części (biała i brązowa).\r\n\r\nPiec w długich foremkach.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (40	,22	,"Masa","Budyń rozetrzec z jajami i wlać na gorące mleko; gotować do zagęstnienia.\r\n\r\nPo ostudzeniu połączyc z masłem.",2)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (41	,22	,"-","Upieczone ciastko podzielić na kromki i przekładać masą, resztą masy posmarować boki i wierzch.\r\n\r\nBabkę polać polewą czekoladową.",3)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (42	,23	,"-","Margarynę z żółtkami i cukrem (3 łyżki) utrzeć, dodać mąke z proszkiem do pieczenia i dobrze ugnieść ciasto. Podzielić je na dwie części - jasną i brązową, następnie włożyć je do lodówki.\r\n\r\nPrzygotować owoce i ubić pianę z białek i cukru (1 szklanka). Na blaszkę nakruszyć białe i brązowe ciasto, na to nałożyć owoce, a następnie pianę.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (43	,24	,"Ciasto","Zagnieść z podanych składników.\r\n\r\nPodzielic na dwie części, zamrozić.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (44	,24	,"Masa","Margarynę z cukrem i żółtkami utrzeć, dodać ser, mąkę, aromat, dobrze utrzeć, dodać ubitą pianę z białek.",2)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (45	,24	,"-","Ciasto poskubać na blaszkę, wylać masę serową, poskubać na nią drugą część ciasta.\r\n\r\nPiec około 40minut.",3)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (46	,25	,"-","Z jaja, cukru, mąki i mleka zagnieść ciasto dodać do niego roztopiony miód i sodę.\r\n\r\nCiasto podzielić na trzy części i upiec.\r\n\r\nNa ostudzone ciasto wlać masę i polać polewać z lukrem.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (47	,26	,"-","Margarynę rozpuścić, wszystkie składniki dobrze utrzeć i dodać margarynę.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (48	,27	,"-","Wszystkie składniki oprócz mąki i jaj rozpuścić na wolnym ogniu, pos ostudzeniu dodać mąkę i żółtka, utrzeć, dodać ubitą pianę z białek.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (49	,28	,"Ciasto","Zagnieść, ostudzić, rozwałkować, lepić jak pierogi, smarować jajem i układać na blaszcze.\r\n\r\nPiec około 25-30minut.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (50	,28	,"Nadzienie","-",2)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (51	,29	,"-","Margarynę, cukier i kakao gotować do rozpuszczenia cukru.\r\n\r\nOstudzić i dodawać po jednym jajku ucierając.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (53	,31	,"-","Wszystkie składniki dobrze utrzeć, podzielić na trzy części, przełożyć marmoladą.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (54	,32	,"-","Żelatynę zalać szklanką wrzącej wody, rozlac do 3 szklanek.\r\n\r\nI wartstwa:\r\n1 szklankę śmietany schłodzić, ubić trzepaczką, dodać 3 łyżki cukru, ubić z 1 porcją żelatyny, wlać do tortownicy i zastudzić.\r\n\r\nII wartswa:\r\n2 jaja rozbić, oddzielić białko od żółtka, ubić białko, dodać 3 łyżki cukru, ubić, dodać kakao i ubić z żółtkami.\r\n\r\nIII wartswa:\r\ntak jak pierwsza. Wszystko zalać galaretką.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (56	,33	,"Masa","Galaretki zrobić w 0.5l wody, wszystko razem zmiksować.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (55	,33	,"-","Ubić żółtka z 3/4 szklanki cukru, dodać 6 łyżek wrzącej wody, następnie ubite białka z 1/4 szklanki cukru.\r\n\r\nUpipeczony biszkopt podzielić na dwie części, przełożyć masą i polać polewać czekoladową.",2)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (57	,34	,"-","Masło włożyć do rondelka i na małym ogniu doprowadzić do wrzenia. W tym czasie ubić całe jaja z cukrem i cukrem waniliowym, następnie dodawać stopniowo mąki z proszkiem do pieczenia. Na koniec dodać aromaty i gorące masło.\r\n\r\nPiec w temperaturze 170 st. C. 35-40minut.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (58	,35	,"-","Kapustę poszatkować, włoszczyznę umyć i zetrzeć na tarce jarzynowej. Wszystko zalać wrzącym Rosołem i gotować pod przykryciem około 10min. Na końcu dodać podsmażoną na maśle cebulę. Mięso wymieszać z fixem do mięsa, dodać jajko i przygotować masę, z której uformować niewielkie okrągłe pulpety. \r\n\r\nNastępnie włożyć je do zupy i gotować na wolnym ogniu około 15min. Gdy zupa jest gotowa zabielić ja zasmażką, dodać równocześnie obrane ze skóry i pokrojone w ćwiartki pomidory oraz przyprawić Delikatem.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (59	,36	,"-","Pokrojoną cebulę lekko podsmażyć na rozgrzanej oliwie, dodać mieloną wołowinę i dalej smażyc intensywnie mieszając, tak aby mięso rozpadło się na drobne cząstki. Następnie zalać mięso Rosołem wołowym, dodając również rozdrobnione uprzednio pomidory wraz z zalewą, ketchum i przyprawy. Całość dusić na wolnym ogniu około 15 minut. Na końcu dodać odsączoną czerwoną fasolę i jeszcze chwilkę gotować lekko mieszając. Tę gestą, pikantną zupę podajemy w małych miseczkach z białym pieczywem.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (60	,37	,"-","Ze składników zrobić ciasto i podzielić na 3 części.\r\n",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (61	,37	,"I część","Rozmarować na blaszce i posmarować marmoladą.",2)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (64	,37	,"-","Na marmoladę zetrzeć zamrożoną część ciasta z kakao.\r\n\r\nUbić białka, dodać cukier puder i kisiele. Na to dodać startą białą masę. \r\n\r\nPiec w gorącym piekarniku.",3)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (13	,4	,"-","Na jedno ciasteczko kładziemy dżem, przykrywamy drugim z pary i dajemy lukier na wierch.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (3	,1	,"-","Ciasto wystudzone przekroić i przełożyć kremem.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (62	,37	,"II część","Włożyć do lodówki.",4)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (63	,37	,"III część","Dodać kakao i włożyć do lodówki.",5)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (28	,13	,"-","Białka ubić z cukrem na sztyną pianę, dodać do neij mąkę, żółtka, proszek i zapach, dokładnie ubić na jednolitą masę.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (52	,30	,"-","Margarynę, cukier, ocet i oliwę utrzeć razem, następnie po jednym dodawać jajka i ucierać, dodawać mąkę i mleko stopniowo.\r\n\r\nPodzielić ciasto na dwie połowy. Na jedną nałożyć utarte jabłka i wlać drugą część.\r\n\r\nPiec około godzinę.",1)'
    execute 'insert into recipe_steps(id, recipe_id, name, description, step_order_no) values (65	,38	,"-","Cebulę obrać, opłukać, drobno pokrajać, usmażyć, dodać mąkę, lekko zarumienić, rozprowadzić zimnym wywarem szybko mieszając trzepaczką, zagotować i gotować około 10 min. na małym ogniu często mieszając. \r\n\r\nSos przetrzeć, połączyć ze śmietaną i musztardą, doprawić do smaku. Sos podawać do potraw mięsnych.",1)'
    
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(1	,1	,1	,2.0	,1	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(2	,2	,1	,1.0	,1	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(3	,3	,1	,1.0	,1	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(4	,4	,10	,1.0	,1	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(5	,5	,1	,0.5	,1	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(6	,6	,6	,2.0	,1	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(7	,7	,6	,2.0	,1	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(8	,8	,6	,2.0	,1	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(10	,3	,1	,2.0	,2	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(11	,1	,1	,0.5	,2	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(12	,2	,1	,0.5	,2	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(13	,10	,10	,1.0	,2	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(14	,11	,10	,1.0	,2	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(15	,4	,10	,4.0	,4	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(16	,2	,1	,1.0	,4	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(17	,12	,6	,1.5	,4	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(18	,13	,6	,1.0	,4	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(19	,14	,3	,0.5	,5	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(20	,11	,10	,1.0	,5	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(21	,15	,6	,2.0	,5	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(22	,12	,6	,2.0	,5	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(23	,2	,1	,0.5	,5	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(24	,16	,11	,1.0	,5	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(25	,17	,9	,1.5	,6	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(26	,18	,10	,2.0	,6	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(27	,19	,15	,10.0	,7	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(28	,20	,15	,10.0	,7	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(29	,21	,6	,2.0	,7	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(30	,4	,10	,2.0	,8	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(31	,10	,10	,2.0	,8	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(32	,2	,1	,0.75	,8	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(33	,2	,1	,0.75	,8	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(34	,22	,5	,1.5	,8	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(35	,13	,6	,1.0	,8	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(36	,19	,15	,20.0	,9	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(37	,3	,1	,2.0	,9	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(38	,23	,11	,0.5	,9	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(40	,24	,6	,2.0	,9	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(41	,25	,10	,2.0	,9	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(42	,26	,10	,1.0	,9	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(43	,27	,13	,2.0	,9	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(44	,28	,10	,1.0	,9	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(45	,29	,9	,0.5	,10	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(46	,16	,11	,1.0	,10	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(47	,10	,10	,5.0	,10	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(48	,25	,10	,5.0	,12	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(49	,30	,1	,1.0	,12	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(50	,31	,15	,50.0	,14	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(51	,3	,1	,1.0	,14	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(52	,32	,15	,20.0	,14	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(53	,23	,11	,1.0	,14	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(54	,29	,9	,1.0	,15	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(55	,14	,3	,0.5	,15	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(56	,33	,15	,5.0	,15	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(57	,4	,10	,2.0	,15	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(58	,31	,15	,25.0	,15	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(61	,36	,16	,0.0	,15	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(62	,37	,16	,0.0	,15	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(63	,38	,16	,0.0	,15	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(64	,39	,15	,12.0	,15	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(66	,42	,9	,0.5	,17	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(67	,31	,15	,25.0	,17	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(68	,20	,15	,5.0	,17	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(69	,43	,16	,0.0	,17	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(70	,6	,6	,4.0	,17	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(71	,44	,16	,0.0	,17	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(72	,25	,10	,2.0	,17	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(73	,1	,1	,1.0	,19	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(76	,4	,10	,1.0	,19	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(77	,46	,16	,0.0	,19	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(78	,47	,16	,0.0	,19	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(79	,36	,16	,0.0	,19	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(80	,48	,16	,0.0	,19	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(81	,49	,16	,0.0	,19	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(82	,50	,10	,1.0	,20	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(84	,51	,16	,0.0	,19	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(85	,51	,16	,0.0	,19	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(86	,52	,9	,3.0	,21	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(87	,53	,16	,5.0	,21	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(88	,54	,16	,3.0	,21	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(89	,55	,16	,2.0	,21	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(90	,56	,17	,6.0	,21	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(91	,36	,16	,0.0	,21	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(92	,57	,16	,0.0	,21	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(93	,5	,1	,0.5	,21	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(94	,58	,1	,0.5	,21	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(95	,59	,10	,0.25	,22	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(96	,60	,3	,1.5	,22	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(97	,60	,3	,2.5	,22	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(98	,2	,1	,2.0	,22	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(99	,61	,5	,1.0	,22	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(100	,62	,10	,1.0	,22	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(101	,20	,15	,30.0	,23	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(102	,63	,15	,10.0	,23	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(103	,63	,15	,20.0	,24	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(104	,64	,16	,1.0	,24	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(106	,66	,16	,0.0	,24	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(107	,67	,6	,0.5	,24	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(108	,14	,3	,0.5	,25	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(109	,68	,16	,4.0	,25	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(110	,64	,16	,1.0	,25	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(111	,31	,15	,9.0	,25	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(112	,69	,18	,0.5	,25	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(113	,70	,15	,3.0	,25	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(114	,71	,15	,3.0	,25	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(115	,63	,15	,20.0	,26	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(116	,68	,16	,3.0	,26	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(117	,72	,6	,4.0	,26	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(118	,73	,5	,1.0	,26	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(119	,74	,9	,0.5	,27	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(120	,75	,1	,0.5	,27	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(121	,64	,16	,3.0	,27	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(122	,76	,6	,2.0	,27	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(123	,16	,11	,0.5	,27	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(124	,2	,1	,1.0	,27	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(125	,77	,16	,0.0	,27	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(126	,64	,16	,5.0	,28	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(129	,73	,5	,2.0	,28	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(130	,80	,19	,0.0	,28	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(131	,2	,1	,1.0	,29	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(132	,81	,19	,4.0	,29	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(133	,82	,6	,4.0	,29	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(134	,73	,5	,1.0	,29	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(135	,1	,1	,0.75	,29	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(136	,83	,9	,0.5	,30	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(137	,23	,11	,1.0	,30	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(138	,2	,1	,1.0	,30	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(139	,84	,19	,0.0	,30	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(140	,85	,19	,0.0	,30	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(141	,86	,19	,0.0	,30	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(142	,24	,6	,4.0	,31	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(143	,87	,6	,1.0	,31	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(144	,88	,6	,2.0	,31	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(145	,89	,15	,5.0	,31	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(146	,90	,6	,2.0	,31	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(147	,21	,6	,3.0	,32	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(148	,16	,11	,1.0	,32	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(149	,91	,20	,200.0	,32	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(150	,80	,19	,0.0	,32	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(151	,14	,3	,0.5	,33	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(152	,12	,6	,1.0	,33	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(153	,92	,6	,1.0	,33	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(154	,11	,10	,2.0	,33	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(155	,16	,11	,1.0	,33	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(156	,30	,1	,1.25	,33	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(157	,81	,19	,5.0	,34	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(158	,2	,1	,1.5	,34	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(159	,1	,1	,2.0	,34	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(160	,73	,5	,1.0	,34	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(161	,5	,1	,1.0	,34	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(162	,93	,1	,1.0	,34	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(163	,88	,6	,2.0	,34	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(164	,1	,1	,1.0	,35	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(165	,94	,1	,0.5	,35	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(166	,16	,11	,0.5	,35	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(167	,81	,19	,4.0	,35	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(168	,73	,5	,1.0	,35	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(169	,95	,10	,1.0	,36	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(170	,14	,3	,0.5	,36	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(171	,23	,11	,1.0	,36	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(172	,80	,19	,0.0	,36	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(173	,81	,19	,7.0	,38	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(174	,16	,11	,1.0	,38	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(175	,2	,1	,1.0	,38	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(176	,96	,1	,1.0	,38	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(177	,97	,1	,1.0	,38	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(178	,73	,5	,1.5	,38	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(179	,31	,15	,26.0	,39	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(180	,81	,19	,4.0	,39	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(181	,98	,6	,10.0	,39	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(182	,82	,6	,10.0	,39	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(183	,63	,15	,26.0	,39	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(184	,13	,6	,1.0	,39	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(185	,14	,3	,0.5	,40	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(186	,21	,6	,4.0	,40	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(188	,99	,10	,1.0	,40	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(189	,81	,19	,2.0	,40	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(190	,100	,11	,1.5	,40	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(191	,29	,9	,0.5	,42	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(192	,81	,19	,4.0	,42	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(193	,21	,6	,3.0	,42	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(194	,2	,1	,1.0	,42	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(195	,88	,6	,1.0	,42	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(196	,73	,5	,1.0	,42	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(197	,16	,11	,1.0	,42	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(198	,101	,19	,0.0	,42	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(199	,29	,9	,0.5	,43	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(200	,16	,11	,1.0	,43	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(201	,73	,5	,2.0	,43	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(202	,2	,1	,0.5	,43	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(203	,102	,6	,3.0	,43	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(204	,81	,19	,5.0	,44	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(205	,87	,6	,1.5	,44	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(206	,103	,9	,1.0	,44	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(207	,2	,1	,1.0	,44	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(208	,104	,19	,0.0	,44	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(209	,23	,11	,1.0	,44	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(210	,81	,19	,1.0	,46	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(211	,71	,15	,15.0	,46	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(212	,63	,15	,45.0	,46	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(213	,90	,6	,2.0	,46	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(214	,105	,6	,5.0	,46	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(215	,106	,15	,5.0	,46	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(216	,107	,5	,1.0	,46	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(217	,2	,1	,1.5	,47	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(218	,88	,6	,3.0	,47	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(219	,3	,1	,0.33	,47	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(220	,81	,19	,4.0	,47	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(221	,1	,1	,2.0	,47	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(222	,73	,5	,1.0	,47	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(223	,16	,11	,1.0	,47	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(224	,81	,19	,4.0	,48	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(225	,2	,1	,1.0	,48	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(226	,97	,1	,1.0	,48	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(227	,96	,1	,1.0	,48	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(228	,73	,5	,1.0	,48	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(229	,108	,19	,1.0	,48	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(230	,88	,6	,3.0	,48	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(231	,90	,6	,1.0	,48	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(232	,23	,11	,1.0	,48	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(233	,29	,9	,0.5	,49	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(234	,21	,6	,3.0	,49	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(235	,81	,19	,2.0	,49	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(236	,90	,6	,6.0	,49	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(237	,109	,6	,4.0	,49	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(238	,110	,19	,0.0	,49	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(239	,73	,5	,1.0	,49	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(240	,111	,19	,1.0	,49	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(241	,17	,9	,0.5	,50	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(242	,108	,19	,0.0	,50	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(243	,21	,6	,3.0	,50	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(244	,112	,19	,0.0	,50	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(245	,16	,11	,1.0	,51	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(246	,21	,6	,5.0	,51	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(247	,88	,6	,2.0	,51	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(248	,113	,19	,2.0	,51	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(249	,16	,11	,0.5	,52	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(250	,81	,19	,4.0	,52	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(251	,2	,1	,1.5	,52	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(252	,1	,1	,3.0	,52	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(253	,73	,5	,2.0	,52	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(255	,67	,6	,2.0	,52	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(256	,80	,19	,0.0	,52	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(257	,3	,1	,0.75	,52	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(261	,29	,9	,1.0	,53	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(262	,117	,10	,0.5	,53	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(263	,2	,1	,1.5	,53	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(265	,102	,6	,4.0	,53	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(266	,16	,11	,1.0	,53	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(268	,108	,19	,0.0	,53	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(269	,120	,19	,0.0	,53	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(270	,121	,6	,1.0	,53	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(271	,122	,6	,5.0	,52	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(272	,76	,6	,4.0	,54	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(273	,123	,1	,2.0	,54	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(274	,21	,6	,6.0	,54	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(275	,88	,6	,3.0	,54	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(276	,81	,19	,2.0	,54	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(277	,81	,19	,6.0	,55	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(278	,2	,1	,1.0	,55	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(279	,1	,1	,1.5	,55	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(280	,73	,5	,2.0	,55	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(284	,124	,19	,2.0	,56	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(285	,125	,19	,2.0	,56	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(286	,60	,3	,0.5	,56	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(287	,126	,19	,0.0	,56	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(288	,81	,19	,5.0	,57	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(289	,1	,1	,1.0	,57	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(290	,2	,1	,1.0	,57	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(292	,127	,1	,0.5	,57	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(293	,128	,6	,2.0	,57	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(294	,108	,19	,0.0	,57	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(295	,73	,5	,1.0	,57	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(296	,129	,15	,25.0	,57	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(297	,88	,6	,2.0	,57	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(298	,130	,15	,30.0	,58	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(299	,131	,22	,0.5	,58	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(300	,81	,19	,1.0	,58	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(301	,132	,11	,4.0	,58	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(302	,133	,23	,1.0	,58	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(303	,134	,24	,1.0	,58	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(304	,135	,10	,3.0	,58	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(305	,136	,10	,4.0	,58	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(306	,137	,19	,0.0	,58	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(307	,109	,6	,1.0	,58	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(308	,138	,22	,1.0	,58	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(309	,139	,9	,0.5	,59	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(310	,140	,11	,1.0	,59	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(311	,135	,10	,4.0	,59	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(312	,141	,25	,1.0	,59	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(313	,142	,26	,0.5	,59	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(314	,143	,6	,4.0	,59	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(315	,122	,6	,4.0	,59	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(316	,144	,25	,2.0	,59	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(317	,137	,19	,0.0	,59	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(318	,145	,5	,1.0	,59	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(319	,146	,19	,0.0	,59	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(320	,1	,1	,5.0	,60	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(321	,147	,19	,1.0	,60	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(322	,148	,27	,1.0	,60	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(323	,16	,11	,2.0	,60	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(324	,149	,28	,10.0	,60	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(325	,4	,10	,8.0	,60	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(326	,10	,10	,8.0	,60	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(328	,25	,10	,8.0	,64	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(329	,71	,15	,40.0	,64	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(330	,151	,10	,2.0	,64	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(331	,22	,19	,0.0	,63	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(333	,1	,1	,1.0	,28	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(334	,2	,1	,1.0	,28	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(336	,17	,19	,0.0	,52	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(337	,152	,20	,350.0	,65	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(338	,91	,20	,50.0	,65	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(339	,135	,15	,8.0	,65	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(340	,39	,15	,4.0	,65	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(341	,1	,15	,3.0	,65	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(342	,36	,19	,0.0	,65	)'
    execute 'insert into step_ingredients (id, product_id, unit_id, amount, recipe_step_id) values(343	,2	,19	,0.0	,65	)'
  end

  def self.down
    execute "DELETE FROM units"
    execute "DELETE FROM products"
    execute "DELETE FROM recipe_steps"
    execute "DELETE FROM recipes"
    execute "DELETE FROM step_ingredients"
    execute "DELETE FROM users"
  end
end
